apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
data:
  APP_NAME: "users-service"
  APP_VERSION: "latest"

  GRPC_PORT: "8080"
  GRPC_TIME: "30s"
  GRPC_TIMEOUT: "5s"
  GRPC_MAX_CONN_IDLE: "15m"
  GRPC_MAX_CONN_AGE: "30m"

  HTTP_PORT: "8081"
  HTTP_TIMEOUT: "5s"
  IDLE_TIMEOUT: "30s"
  SHUTDOWN_TIMEOUT: "30s"

  REDIS_ADDRESS: "users-service-redis-master:6379"
  REDIS_DIAL_TIMEOUT: "10s"
  REDIS_READ_TIMEOUT: "50ms"
  REDIS_WRITE_TIMEOUT: "50ms"
  REDIS_MAX_RETRIES: "-1"
  REDIS_MIN_RETRY_BACKOFF: "5ms"
  REDIS_MAX_RETRY_BACKOFF: "15ms"
  REDIS_POOL_SIZE: "100"
  REDIS_MIN_IDLE_CONS: "20"
  REDIS_POOL_TIMEOUT: "10ms"

  DB_USERNAME: "postgres"
  DB_PASSWORD: "root_password"
  DB_HOST: "users-service-postgresql"
  DB_PORT: "5432"
  DB_NAME: "users_db"
  DB_MAX_CONN: "100"
  DB_MIN_CONN: "5"
  DB_CONN_TIMEOUT: "10s"
  DB_MAX_CONN_TIME: "1h"
  DB_MAX_CONN_IDLE_TIME: "5m"
  DB_HEALTH_CHECK_PERIOD: "10m"

  OTEL_IS_TLS: "false"
  OTEL_ENDPOINT: "alloy.monitoring.svc.cluster.local:4317"
  OTEL_PYROSCOPE_ENDPOINT: "http://alloy.monitoring.svc.cluster.local:4040"
  OTEL_TIMEOUT: "15s"