apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: users-service

resources:
  - configmap.yaml
  - deployment.yaml
  - sa.yaml
  - service.yaml

patches:
  - target:
      kind: Deployment
      name: users-service
    patch: |-
      - op: add
        path: /spec/template/spec/initContainers
        value:
          - name: wait-redis
            image: busybox:1.36
            command: ["sh", "-c", "until nc -w 2 $(REDIS_ADDRESS); do echo Waiting for redis; sleep 2; done;"]
            envFrom:
              - configMapRef:
                  name: users-service-config
          - name: wait-postgresql
            image: busybox:1.36
            command: ["sh", "-c", "until nc -w 2 $(DB_HOST) $(DB_PORT); do echo Waiting for postgres; sleep 2; done;"]
            envFrom:
              - configMapRef:
                  name: users-service-config
          - name: run-migrations
            image: users-service-image
            command: ["/migrations/migrate", "-path=/migrations/schemes", "-database=postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable", "up"]
            envFrom:
              - configMapRef:
                  name: users-service-config