services:
  app:
    container_name: app.${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HEALTH_PORT}:${HEALTH_PORT}"
    environment:
      - APP_NAME=${APP_NAME}
      - DB_URL=${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
      - DB_DRIVER=${DB_DRIVER}
      - GRPC_PORT=${GRPC_PORT}
      - HEALTH_PORT=${HEALTH_PORT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - IDLE_TIMEOUT=${IDLE_TIMEOUT}
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - DB_MAX_CONN=${DB_MAX_CONN}
      - DB_MAX_CONN_TIME=${DB_MAX_CONN_TIME}
      - REDIS_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
      - CLIENT_READ_TIMEOUT=${CLIENT_READ_TIMEOUT}
      - CLIENT_WRITE_TIMEOUT=${CLIENT_WRITE_TIMEOUT}
      - CLIENT_MAX_IDLE=${CLIENT_MAX_IDLE}
    depends_on:
      - db
      - redis
    networks:
      - app

  db:
    container_name: db.${APP_NAME}
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init-outbox.sql:/docker-entrypoint-initdb.d/init-outbox.sql
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: redis.${APP_NAME}
    image: redis:8.4.0-alpine
    volumes:
      - redis_data:/redis_data
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    expose:
      - '${REDIS_PORT}'

volumes:
  db_data:
  redis_data:

networks:
  app:
    driver: bridge