services:
  app:
    container_name: app.${APP_NAME}
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${DIAGNOSTIC_PORT}:${DIAGNOSTIC_PORT}"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      master:
        condition: service_healthy
      replica1:
        condition: service_healthy
      replica2:
        condition: service_healthy
    networks:
      - app

  redis:
    container_name: redis.${APP_NAME}
    image: redis:8.4.0
    volumes:
      - redis_data:/redis_data
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    expose:
      - '${REDIS_PORT}'

  master:
    build: .docker/pg-master
    container_name: master
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "6000:5432"
    volumes:
      - master-data:/var/lib/postgresql/data
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  replica1:
    build: .docker/pg-replica
    container_name: replica1
    depends_on:
      - master
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPASSWORD: root
      REPLICA_NAME: replica1
    ports:
      - "6001:5432"
    volumes:
      - replica1-data:/var/lib/postgresql/data
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  replica2:
    build: .docker/pg-replica
    container_name: replica2
    depends_on:
      - master
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPASSWORD: root
      REPLICA_NAME: replica2
    ports:
      - "6002:5432"
    volumes:
      - replica2-data:/var/lib/postgresql/data
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  otel:
    container_name: otel.${APP_NAME}
    image: grafana/otel-lgtm:latest
    ports:
      - '${OTEL_GRAFANA_PORT}:3000'
      - '${OTEL_GRPC_PORT}:4317'
    networks:
      - app
    volumes:
      - ./.docker/otel/data:/data
    environment:
      - ENABLE_LOGS_ALL=true
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
  master-data:
  replica1-data:
  replica2-data:

networks:
  app:
    driver: bridge