services:
  app:
    container_name: app.${APP_NAME}
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HEALTH_PORT}:${HEALTH_PORT}"
    environment:
      - APP_NAME=${APP_NAME}
      - DB_URL=${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
      - DB_DRIVER=${DB_DRIVER}
      - GRPC_PORT=${GRPC_PORT}
      - HEALTH_PORT=${HEALTH_PORT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - IDLE_TIMEOUT=${IDLE_TIMEOUT}
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - DB_MAX_CONN=${DB_MAX_CONN}
      - DB_MAX_CONN_TIME=${DB_MAX_CONN_TIME}
      - REDIS_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
      - CLIENT_READ_TIMEOUT=${CLIENT_READ_TIMEOUT}
      - CLIENT_WRITE_TIMEOUT=${CLIENT_WRITE_TIMEOUT}
      - CLIENT_MAX_IDLE=${CLIENT_MAX_IDLE}
      - MQ_URL=amqp://${MQ_USERNAME}:${MQ_PASSWORD}@rabbitmq:${MQ_PORT}/
    depends_on:
      - db
      - redis
      - rabbitmq
      - sequin
    networks:
      - app

  redis:
    container_name: redis.${APP_NAME}
    image: redis:8.4.0
    volumes:
      - redis_data:/redis_data
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    expose:
      - '${REDIS_PORT}'

  rabbitmq:
    container_name: rabbitmq.${APP_NAME}
    image: rabbitmq:4.2.0-management
    ports:
      - '${MQ_PORT}:5672'
      - '${MQ_ADMIN_PORT}:15672'
    networks:
      - app
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 30

  db:
    container_name: db.${APP_NAME}
    image: postgres:16
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init-outbox.sql:/docker-entrypoint-initdb.d/init-outbox.sql
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  sequin:
    container_name: sequin.${APP_NAME}
    image: sequin/sequin:latest
    ports:
      - '${SEQUIN_PORT}:7376'
    networks:
      - app
    environment:
      - PG_HOSTNAME=db
      - PG_DATABASE=${DB_DATABASE}
      - PG_PORT=${DB_PORT}
      - PG_USERNAME=${DB_USERNAME}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_POOL_SIZE=${DB_MAX_CONN}
      - SECRET_KEY_BASE=wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If
      - VAULT_KEY=2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=
      - REDIS_URL=redis://redis:${REDIS_PORT}
      - CONFIG_FILE_PATH=/config/main.yml
      - SEQUIN_EMAIL=${SEQUIN_EMAIL}
      - SEQUIN_PASSWORD=${SEQUIN_PASSWORD}
      - MQ_USERNAME=${MQ_USERNAME}
      - MQ_PASSWORD=${MQ_PASSWORD}
      - MQ_PORT=${MQ_PORT}
    volumes:
      - ./docker/sequin/sequin.yml:/config/main.yml
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  db_data:
  redis_data:
  rabbitmq_data:

networks:
  app:
    driver: bridge