// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mock/mock_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/go-list-templ/grpc/internal/core/domain/entity"
	event "github.com/go-list-templ/grpc/internal/core/domain/event"
	paginate "github.com/go-list-templ/grpc/pkg/paginate"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockUserRepo) All(arg0 context.Context, arg1 paginate.Paginate) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0, arg1)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockUserRepoMockRecorder) All(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockUserRepo)(nil).All), arg0, arg1)
}

// Store mocks base method.
func (m *MockUserRepo) Store(arg0 context.Context, arg1 entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), arg0, arg1)
}

// MockOutboxRepo is a mock of OutboxRepo interface.
type MockOutboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepoMockRecorder
	isgomock struct{}
}

// MockOutboxRepoMockRecorder is the mock recorder for MockOutboxRepo.
type MockOutboxRepoMockRecorder struct {
	mock *MockOutboxRepo
}

// NewMockOutboxRepo creates a new mock instance.
func NewMockOutboxRepo(ctrl *gomock.Controller) *MockOutboxRepo {
	mock := &MockOutboxRepo{ctrl: ctrl}
	mock.recorder = &MockOutboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepo) EXPECT() *MockOutboxRepoMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockOutboxRepo) Publish(arg0 context.Context, arg1 event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockOutboxRepoMockRecorder) Publish(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockOutboxRepo)(nil).Publish), arg0, arg1)
}
