account:
  name: sequin

users:
  - account: sequin
    email: ${SEQUIN_EMAIL}
    password: ${SEQUIN_PASSWORD}

functions:
  - name: record.message
    type: path
    path: record.message

databases:
  - name: ${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    hostname: ${PG_HOSTNAME}
    database: ${PG_DATABASE}
    port: ${PG_PORT}
    slot_name: sequin_slot
    publication_name: sequin_pub

sinks:
  - name: outbox
    database: ${PG_DATABASE}
    source:
      include_table_names:
        - public.outbox
    actions:
      - insert
    transform: record.message
    batch_size: 10
    destination:
      type: rabbitmq
      host: rabbitmq
      virtual_host: /
      username: ${MQ_USERNAME}
      password: ${MQ_PASSWORD}
      port: ${MQ_PORT}
      exchange: events