services:
  test-stress:
    container_name: test-stress
    build:
      context: .
      dockerfile: .docker/test-stress/Dockerfile
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - app
    networks:
      - app

networks:
  app:
    driver: bridge
