services:
  test-stress:
    container_name: test-stress
    build:
      context: .
      dockerfile: .docker/test-stress/Dockerfile
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      - app
    networks:
      - app

networks:
  app:
    driver: bridge
