services:
  test:
    container_name: test
    build:
      context: .
      dockerfile: .docker/test-integration/Dockerfile
    depends_on:
      - app
    networks:
      - app

networks:
  app:
    driver: bridge
