apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-migrate-rev{{ .Release.Revision }}"
  annotations:
    werf.io/weight: "20"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: migrate
          image: {{ .Values.werf.image.app }}
          command:
            - /migrations/migrate
            - -path=/migrations/schemes
            - -database=postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable
            - up
          env:
            - name: DB_HOST
              value: "{{ .Release.Name }}-{{ .Values.postgresql.host }}"
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: DB_PORT
              value: {{ .Values.postgresql.port | quote }}