auth:
  database: users_db
  username: postgres
  password: "root_password"

architecture: standalone

primary:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi