postgresql:
  enabled: true
  architecture: standalone
  host: postgresql
  port: 5432
  auth:
    database: users_db
    username: postgres
    password: "root_password"
  primary:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 512Mi