apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  APP_NAME: {{ .Values.werf.name | quote }}
  APP_VERSION: {{ .Values.werf.image.app | quote}}

  GRPC_PORT: {{ .Values.app.grpc.port | quote }}
  GRPC_TIME: {{ .Values.app.grpc.time | quote }}
  GRPC_TIMEOUT: {{ .Values.app.grpc.timeout | quote }}
  GRPC_MAX_CONN_IDLE: {{ .Values.app.grpc.maxIdle | quote }}
  GRPC_MAX_CONN_AGE: {{ .Values.app.grpc.maxAge | quote }}

  DIAGNOSTIC_PORT: {{ .Values.app.diagnostic.port | quote }}
  HTTP_TIMEOUT: {{ .Values.app.diagnostic.httpTimeout | quote }}
  IDLE_TIMEOUT: {{ .Values.app.diagnostic.idleTimeout | quote }}
  SHUTDOWN_TIMEOUT: {{ .Values.app.shutdownTimeout | quote }}

  REDIS_ADDRESS: {{ .Values.redis.url | quote }}
  REDIS_DIAL_TIMEOUT: {{ .Values.redis.dialTimeout | quote }}
  REDIS_READ_TIMEOUT: {{ .Values.redis.readTimeout | quote }}
  REDIS_WRITE_TIMEOUT: {{ .Values.redis.writeTimeout | quote }}
  REDIS_MAX_RETRIES: {{ .Values.redis.maxRetries | quote }}
  REDIS_MIN_RETRY_BACKOFF: {{ .Values.redis.minRetryBackoff | quote }}
  REDIS_MAX_RETRY_BACKOFF: {{ .Values.redis.maxRetryBackoff | quote }}
  REDIS_POOL_SIZE: {{ .Values.redis.pool.size | quote }}
  REDIS_MIN_IDLE_CONS: {{ .Values.redis.pool.minIdle | quote }}
  REDIS_POOL_TIMEOUT: {{ .Values.redis.pool.timeout | quote }}

  DB_URL: {{ .Values.db.url | quote }}
  DB_MAX_CONN: {{ .Values.db.maxConn | quote }}
  DB_MIN_CONN: {{ .Values.db.minConn | quote }}
  DB_CONN_TIMEOUT: {{ .Values.db.connTimeout | quote }}
  DB_MAX_CONN_TIME: {{ .Values.db.maxConnTime | quote }}
  DB_MAX_CONN_IDLE_TIME: {{ .Values.db.maxConnIdleTime | quote }}
  DB_HEALTH_CHECK_PERIOD: {{ .Values.db.healthCheckPeriod | quote }}

  OTEL_IS_TLS: {{ .Values.otel.isTls | quote }}
  OTEL_ENDPOINT: {{ .Values.otel.url | quote}}