apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  APP_NAME: {{ .Chart.Name | quote }}
  APP_VERSION: {{ .Values.werf.image.app | quote}}

  GRPC_PORT: {{ .Values.app.grpc.port | quote }}
  GRPC_TIME: {{ .Values.app.grpc.time | quote }}
  GRPC_TIMEOUT: {{ .Values.app.grpc.timeout | quote }}
  GRPC_MAX_CONN_IDLE: {{ .Values.app.grpc.maxIdle | quote }}
  GRPC_MAX_CONN_AGE: {{ .Values.app.grpc.maxAge | quote }}

  HTTP_PORT: {{ .Values.app.http.port | quote }}
  HTTP_TIMEOUT: {{ .Values.app.http.httpTimeout | quote }}
  IDLE_TIMEOUT: {{ .Values.app.http.idleTimeout | quote }}
  SHUTDOWN_TIMEOUT: {{ .Values.app.shutdownTimeout | quote }}

  REDIS_ADDRESS: "{{ .Release.Name }}-{{ .Values.redis.host }}:{{ .Values.redis.port }}"
  REDIS_DIAL_TIMEOUT: {{ .Values.app.redis.dialTimeout | quote }}
  REDIS_READ_TIMEOUT: {{ .Values.app.redis.readTimeout | quote }}
  REDIS_WRITE_TIMEOUT: {{ .Values.app.redis.writeTimeout | quote }}
  REDIS_MAX_RETRIES: {{ .Values.app.redis.maxRetries | quote }}
  REDIS_MIN_RETRY_BACKOFF: {{ .Values.app.redis.minRetryBackoff | quote }}
  REDIS_MAX_RETRY_BACKOFF: {{ .Values.app.redis.maxRetryBackoff | quote }}
  REDIS_POOL_SIZE: {{ .Values.app.redis.pool.size | quote }}
  REDIS_MIN_IDLE_CONS: {{ .Values.app.redis.pool.minIdle | quote }}
  REDIS_POOL_TIMEOUT: {{ .Values.app.redis.pool.timeout | quote }}

  DB_HOST: "{{ .Release.Name }}-{{ .Values.postgresql.host }}"
  DB_PORT: {{ .Values.postgresql.port | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  DB_MAX_CONN: {{ .Values.app.db.maxConn | quote }}
  DB_MIN_CONN: {{ .Values.app.db.minConn | quote }}
  DB_CONN_TIMEOUT: {{ .Values.app.db.connTimeout | quote }}
  DB_MAX_CONN_TIME: {{ .Values.app.db.maxConnTime | quote }}
  DB_MAX_CONN_IDLE_TIME: {{ .Values.app.db.maxConnIdleTime | quote }}
  DB_HEALTH_CHECK_PERIOD: {{ .Values.app.db.healthCheckPeriod | quote }}

  OTEL_IS_TLS: {{ .Values.telemetry.collector.isTls | quote }}
  OTEL_ENDPOINT: {{ .Values.telemetry.collector.url | quote}}
  OTEL_PYROSCOPE_ENDPOINT: {{ .Values.telemetry.pyroscope.url | quote}}
  OTEL_TIMEOUT: {{ .Values.telemetry.collector.timeout | quote }}