apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: app
          image: {{ .Values.werf.image.app }}
          command: [ "/bin/app" ]
          ports:
            - containerPort: {{ .Values.app.grpc.port }}
            - containerPort: {{ .Values.app.diagnostic.port }}
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config