apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    werf.io/weight: "30"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.werf.image.app }}
          command: [ "/bin/app" ]
          ports:
            - name: {{ .Values.app.grpc.name }}
              containerPort: {{ .Values.app.grpc.port }}
              protocol: {{ .Values.app.grpc.protocol }}
            - name: {{ .Values.app.http.name }}
              containerPort: {{ .Values.app.http.port }}
              protocol: {{ .Values.app.http.protocol }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.app.http.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.app.http.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
            successThreshold: 1
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
          resources:
            requests:
              cpu: {{ $.Values.app.requests.cpu }}
              memory: {{ $.Values.app.requests.memory}}
            limits:
              cpu: {{ $.Values.app.limits.cpu }}
              memory: {{ $.Values.app.limits.memory }}