apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: app
          image: {{ .Values.werf.image.app }}
          command: [ "/bin/app" ]
          ports:
            - name: grpc
              containerPort: {{ .Values.app.grpc.port }}
            - name: http
              containerPort: {{ .Values.app.http.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.app.http.port }}
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.app.http.port }}
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.app.http.port }}
            periodSeconds: 2
            failureThreshold: 30
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
          resources:
            requests:
              cpu: {{ $.Values.app.requests.cpu }}
              memory: {{ $.Values.app.requests.memory}}
            limits:
              cpu: {{ $.Values.app.limits.cpu }}
              memory: {{ $.Values.app.limits.memory }}