apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
    - {{ .Chart.Name }}
  http:
    - name: "grpc"
      match:
        - port: {{ .Values.app.grpc.port }}
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: {{ .Values.app.grpc.port }}
    - name: "http-diag"
      match:
        - port: {{ .Values.app.http.port }}
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: {{ .Values.app.http.port }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Chart.Name }}
spec:
  host: {{ .Chart.Name }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN # Решает проблему балансировки gRPC