apiVersion: v2
name: users-service
version: 1.0.0

dependencies:
  - name: base
    version: "1.29.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled
  - name: istiod
    version: "1.29.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled
  - name: postgresql
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "25.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled