appName: "users"
replicaCount: 3

app:
  grpc:
    port: 8080
    time: "30s"
    timeout: "5s"
    maxIdle: "15m"
    maxAge: "30m"
  diagnostic:
    port: 8081
    httpTimeout: "5s"
    idleTimeout: "30s"
  shutdownTimeout: "30s"

redis:
  dialTimeout: "50ms"
  readTimeout: "50ms"
  writeTimeout: "50ms"
  maxRetries: -1
  minRetryBackoff: "5ms"
  maxRetryBackoff: "15ms"
  pool:
    size: 100
    minIdle: 20
    timeout: "10ms"

db:
  username: "postgres"
  password: "root"
  port: 5432
  maxConn: 100
  minConn: 5
  connTimeout: "10s"
  maxConnTime: "1h"
  maxConnIdleTime: "5m"
  healthCheckPeriod: "10m"

otel:
  grafanaPort: 3000
  grpcPort: 4317
  isTls: false

externalInfra:
  dbHost: "global-db"
  redisHost: "global-redis"
  otelHost: "otel-lgtm"