name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run hadolint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          config_file: ".docker/hadolint/hadolint.yaml"
          error_level: 1
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1
          args: > 
            run --config=.docker/golangci/.golangci.yml


