name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  helm-lint:
    name: helm lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install werf
        uses: werf/actions/install@v2
      - name: Run script
        run: make helm-lint

  code-lint:
    name: lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0
          args: --config=lint.yml
