name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tests:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run Tests
        run: |
          make copy
          make test-cmd

  test-coverage:
    name: coverage test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run Test Coverage
        run: |
          make copy
          make test-coverage-cmd

  test-integraion:
    name: integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Test Integration
        run: |
          make copy
          make test-integration