name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run Unit Tests
        run: make unit-test

  coverage-test:
    name: coverage test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run Test Coverage
        run: make test-coverage-cmd

#  test-integration:
#    name: integration test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - name: Run Test Integration
#        run: |
#          cp .env.example .env
#          make test-integration